title: Machine Learning Competitions Deadlines
description: Deadlines and prizes list for the AI competitions
author: Narek Maloyan

domain: "aideadlin.es"
baseurl: ""

twitter_hashtag: machinelearning
github_username: paperswithcode
github_repo: ai-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
